sudo: false

cache:
  directories:
  - $HOME/.m2/repository

language: java
jdk:
- openjdk6
- oraclejdk7
- oraclejdk8

env:
  global:
  - secure: HZwse16DnntqzIUQxphg/rawEMk3Os5eZ3EvRakYDGqVlyZgRMUtzROMplCQmZPo0y7kirFkVOVTGstE12p4FHr6fT+CX3AQRdshm/l85JILGOMoUkFLSJ3Mgz4AqJoiMpqi13X4ihRVZOQ+wf8fMlbqbSdb+/JpeBzp+D6qiRk=
  - secure: U2g7Z11V1CRXc/2KtC09e6mSYRiRuFKJ4snJivdfCCQtT+X7bCtMs3GA5XtHYyq1XBa7/AcgFTOGGoWHlI3iSAi96WNyKJEnza7JB+NEYwVzJOMHKfW7AYMgzfqJEH3U9DMuaSdUAPP1+4CzzB+bKxQIha28+xA97l3V15zZaes=

before_install:
- echo "<settings><servers><server><id>sonatype-oss-nexus-snapshots</id><username>\${env.SONATYPE_USER}</username><password>\${env.SONATYPE_PASS}</password></server></servers></settings>"
  > ~/.m2/deploy-settings.xml

install:
  - mvn clean deploy -U --settings ~/.m2/deploy-settings.xml
